# Generated by pyfloyd version 0.19.1.dev0
#    https://github.com/dpranke/pyfloyd
#    `pyfloyd -o json5/parser.py -c json5/json5.g`

import re
from typing import Any, Dict, NamedTuple, Optional
import unicodedata


Externs = Optional[Dict[str, Any]]

# pylint: disable=too-many-lines


class _ParsingRuntimeError(Exception):
    pass


class Result(NamedTuple):
    """The result returned from a `parse()` call.

    If the parse is successful, `val` will contain the returned value, if any
    and `pos` will indicate the point in the text where the parser stopped.
    If the parse is unsuccessful, `err` will contain a string describing
    any errors that occurred during the parse and `pos` will indicate
    the location of the farthest error in the text.
    """

    val: Any = None
    err: Optional[str] = None
    pos: Optional[int] = None


def parse(
    text: str, path: str = '<string>', externs: Externs = None
) -> Result:
    """Parse a given text and return the result.

    If the parse was successful, `result.val` will be the returned value
    from the parse, and `result.pos` will indicate where the parser
    stopped when it was done parsing.

    If the parse is unsuccessful, `result.err` will be a string describing
    any errors found in the text, and `result.pos` will indicate the
    furthest point reached during the parse.

    If the optional `path` is provided it will be used in any error
    messages to indicate the path to the filename containing the given
    text.
    """
    return _Parser(text, path).parse(externs)


class _Parser:
    def __init__(self, text, path):
        self._text = text
        self._end = len(self._text)
        self._errpos = 0
        self._expected_externs = {'strict'}
        self._externs = {}
        self._failed = False
        self._path = path
        self._pos = 0
        self._val = None
        self._regexps = {}

    def parse(self, externs: Externs = None):
        self._externs = externs or {}
        errors = self._check_externs()
        if errors:
            return Result(None, errors, 0)

        try:
            self._r_grammar()
            if self._failed:
                return Result(None, self._err_str(), self._errpos)
            return Result(self._val, None, self._pos)
        except _ParsingRuntimeError as e:  # pragma: no cover
            lineno, _ = self._err_offsets()
            return Result(
                None,
                self._path + ':' + str(lineno) + ' ' + str(e),
                self._errpos,
            )

    def _r_grammar(self):
        self._r_value()
        if self._failed:
            return
        v__1 = self._val
        self._r__filler()
        self._r_end()
        if self._failed:
            return
        self._succeed(v__1)

    def _r_value(self):
        p = self._pos
        self._s_value_1()
        if not self._failed:
            return
        self._rewind(p)
        self._s_value_2()
        if not self._failed:
            return
        self._rewind(p)
        self._s_value_3()
        if not self._failed:
            return
        self._rewind(p)
        self._s_value_4()
        if not self._failed:
            return
        self._rewind(p)
        self._s_value_6()
        if not self._failed:
            return
        self._rewind(p)
        self._s_value_7()
        if not self._failed:
            return
        self._rewind(p)
        self._s_value_8()

    def _s_value_1(self):
        self._r__filler()
        self._str('null')
        if self._failed:
            return
        self._succeed('None')

    def _s_value_2(self):
        self._r__filler()
        self._str('true')
        if self._failed:
            return
        self._succeed('True')

    def _s_value_3(self):
        self._r__filler()
        self._str('false')
        if self._failed:
            return
        self._succeed('False')

    def _s_value_4(self):
        self._s_value_5()
        if self._failed:
            return
        v__1 = self._val
        self._succeed(['number', v__1])

    def _s_value_5(self):
        self._r__filler()
        self._r_num_literal()

    def _s_value_6(self):
        self._r_object()
        if self._failed:
            return
        v__1 = self._val
        self._succeed(['object', v__1])

    def _s_value_7(self):
        self._r_array()
        if self._failed:
            return
        v__1 = self._val
        self._succeed(['array', v__1])

    def _s_value_8(self):
        self._s_value_9()
        if self._failed:
            return
        v__1 = self._val
        self._succeed(['string', v__1])

    def _s_value_9(self):
        self._r__filler()
        self._r_string()

    def _r_object(self):
        p = self._pos
        self._s_object_1()
        if not self._failed:
            return
        self._rewind(p)
        self._s_object_2()

    def _s_object_1(self):
        self._r__filler()
        self._ch('{')
        if self._failed:
            return
        self._r_member_list()
        if self._failed:
            return
        v__2 = self._val
        self._r__filler()
        self._ch('}')
        if self._failed:
            return
        self._succeed(v__2)

    def _s_object_2(self):
        self._r__filler()
        self._ch('{')
        if self._failed:
            return
        self._r__filler()
        self._ch('}')
        if self._failed:
            return
        self._succeed([])

    def _r_array(self):
        p = self._pos
        self._s_array_1()
        if not self._failed:
            return
        self._rewind(p)
        self._s_array_2()

    def _s_array_1(self):
        self._r__filler()
        self._ch('[')
        if self._failed:
            return
        self._r_element_list()
        if self._failed:
            return
        v__2 = self._val
        self._r__filler()
        self._ch(']')
        if self._failed:
            return
        self._succeed(v__2)

    def _s_array_2(self):
        self._r__filler()
        self._ch('[')
        if self._failed:
            return
        self._r__filler()
        self._ch(']')
        if self._failed:
            return
        self._succeed([])

    def _r_string(self):
        p = self._pos
        self._s_string_1()
        if not self._failed:
            return
        self._rewind(p)
        self._s_string_3()

    def _s_string_1(self):
        self._r_squote()
        if self._failed:
            return
        self._s_string_2()
        v__2 = self._val
        self._r_squote()
        if self._failed:
            return
        self._succeed(self._fn_cat(v__2))

    def _s_string_2(self):
        vs = []
        while True:
            p = self._pos
            self._r_sqchar()
            if self._failed or self._pos == p:
                self._rewind(p)
                break
            vs.append(self._val)
        self._succeed(vs)

    def _s_string_3(self):
        self._r_dquote()
        if self._failed:
            return
        self._s_string_4()
        v__2 = self._val
        self._r_dquote()
        if self._failed:
            return
        self._succeed(self._fn_cat(v__2))

    def _s_string_4(self):
        vs = []
        while True:
            p = self._pos
            self._r_dqchar()
            if self._failed or self._pos == p:
                self._rewind(p)
                break
            vs.append(self._val)
        self._succeed(vs)

    def _r_sqchar(self):
        p = self._pos
        self._s_sqchar_1()
        if not self._failed:
            return
        self._rewind(p)
        self._s_sqchar_2()
        if not self._failed:
            return
        self._rewind(p)
        self._s_sqchar_3()
        if not self._failed:
            return
        self._rewind(p)
        self._s_sqchar_7()

    def _s_sqchar_1(self):
        self._r_bslash()
        if self._failed:
            return
        self._r_esc_char()
        if self._failed:
            return
        v__2 = self._val
        self._succeed(v__2)

    def _s_sqchar_2(self):
        self._r_bslash()
        if self._failed:
            return
        self._r_eol()
        if self._failed:
            return
        self._succeed('')

    def _s_sqchar_3(self):
        self._s_sqchar_4()
        if self._failed:
            return
        self._s_sqchar_5()
        if self._failed:
            return
        self._s_sqchar_6()
        if self._failed:
            return
        self._r_any()
        if self._failed:
            return
        v__4 = self._val
        self._succeed(v__4)

    def _s_sqchar_4(self):
        p = self._pos
        errpos = self._errpos
        self._r_bslash()
        if self._failed:
            self._succeed(None, p)
        else:
            self._rewind(p)
            self._errpos = errpos
            self._fail()

    def _s_sqchar_5(self):
        p = self._pos
        errpos = self._errpos
        self._r_squote()
        if self._failed:
            self._succeed(None, p)
        else:
            self._rewind(p)
            self._errpos = errpos
            self._fail()

    def _s_sqchar_6(self):
        p = self._pos
        errpos = self._errpos
        self._r_eol()
        if self._failed:
            self._succeed(None, p)
        else:
            self._rewind(p)
            self._errpos = errpos
            self._fail()

    def _s_sqchar_7(self):
        v = not self._externs['strict']
        if v is True:
            self._succeed(v)
        elif v is False:
            self._fail()
        else:
            raise _ParsingRuntimeError('Bad predicate value')
        if self._failed:
            return
        self._range('\x00', '\x1f')

    def _r_dqchar(self):
        p = self._pos
        self._s_dqchar_1()
        if not self._failed:
            return
        self._rewind(p)
        self._s_dqchar_2()
        if not self._failed:
            return
        self._rewind(p)
        self._s_dqchar_3()
        if not self._failed:
            return
        self._rewind(p)
        self._s_dqchar_7()

    def _s_dqchar_1(self):
        self._r_bslash()
        if self._failed:
            return
        self._r_esc_char()
        if self._failed:
            return
        v__2 = self._val
        self._succeed(v__2)

    def _s_dqchar_2(self):
        self._r_bslash()
        if self._failed:
            return
        self._r_eol()
        if self._failed:
            return
        self._succeed('')

    def _s_dqchar_3(self):
        self._s_dqchar_4()
        if self._failed:
            return
        self._s_dqchar_5()
        if self._failed:
            return
        self._s_dqchar_6()
        if self._failed:
            return
        self._r_any()
        if self._failed:
            return
        v__4 = self._val
        self._succeed(v__4)

    def _s_dqchar_4(self):
        p = self._pos
        errpos = self._errpos
        self._r_bslash()
        if self._failed:
            self._succeed(None, p)
        else:
            self._rewind(p)
            self._errpos = errpos
            self._fail()

    def _s_dqchar_5(self):
        p = self._pos
        errpos = self._errpos
        self._r_dquote()
        if self._failed:
            self._succeed(None, p)
        else:
            self._rewind(p)
            self._errpos = errpos
            self._fail()

    def _s_dqchar_6(self):
        p = self._pos
        errpos = self._errpos
        self._r_eol()
        if self._failed:
            self._succeed(None, p)
        else:
            self._rewind(p)
            self._errpos = errpos
            self._fail()

    def _s_dqchar_7(self):
        v = not self._externs['strict']
        if v is True:
            self._succeed(v)
        elif v is False:
            self._fail()
        else:
            raise _ParsingRuntimeError('Bad predicate value')
        if self._failed:
            return
        self._range('\x00', '\x1f')

    def _r_bslash(self):
        self._ch('\\')

    def _r_squote(self):
        self._ch("'")

    def _r_dquote(self):
        self._ch('"')

    def _r_eol(self):
        p = self._pos
        self._s_eol_1()
        if not self._failed:
            return
        self._rewind(p)
        self._ch('\r')
        if not self._failed:
            return
        self._rewind(p)
        self._ch('\n')
        if not self._failed:
            return
        self._rewind(p)
        self._ch('\u2028')
        if not self._failed:
            return
        self._rewind(p)
        self._ch('\u2029')

    def _s_eol_1(self):
        self._ch('\r')
        if self._failed:
            return
        self._ch('\n')

    def _r_esc_char(self):
        p = self._pos
        self._s_esc_char_1()
        if not self._failed:
            return
        self._rewind(p)
        self._s_esc_char_2()
        if not self._failed:
            return
        self._rewind(p)
        self._s_esc_char_3()
        if not self._failed:
            return
        self._rewind(p)
        self._s_esc_char_4()
        if not self._failed:
            return
        self._rewind(p)
        self._s_esc_char_5()
        if not self._failed:
            return
        self._rewind(p)
        self._s_esc_char_6()
        if not self._failed:
            return
        self._rewind(p)
        self._s_esc_char_7()
        if not self._failed:
            return
        self._rewind(p)
        self._s_esc_char_8()
        if not self._failed:
            return
        self._rewind(p)
        self._s_esc_char_9()
        if not self._failed:
            return
        self._rewind(p)
        self._s_esc_char_10()
        if not self._failed:
            return
        self._rewind(p)
        self._s_esc_char_13()
        if not self._failed:
            return
        self._rewind(p)
        self._r_hex_esc()
        if not self._failed:
            return
        self._rewind(p)
        self._r_unicode_esc()

    def _s_esc_char_1(self):
        self._ch('b')
        if self._failed:
            return
        self._succeed('\b')

    def _s_esc_char_2(self):
        self._ch('f')
        if self._failed:
            return
        self._succeed('\f')

    def _s_esc_char_3(self):
        self._ch('n')
        if self._failed:
            return
        self._succeed('\n')

    def _s_esc_char_4(self):
        self._ch('r')
        if self._failed:
            return
        self._succeed('\r')

    def _s_esc_char_5(self):
        self._ch('t')
        if self._failed:
            return
        self._succeed('\t')

    def _s_esc_char_6(self):
        self._ch('v')
        if self._failed:
            return
        self._succeed('\v')

    def _s_esc_char_7(self):
        self._r_squote()
        if self._failed:
            return
        self._succeed("'")

    def _s_esc_char_8(self):
        self._r_dquote()
        if self._failed:
            return
        self._succeed('"')

    def _s_esc_char_9(self):
        self._r_bslash()
        if self._failed:
            return
        self._succeed('\\')

    def _s_esc_char_10(self):
        self._s_esc_char_11()
        if self._failed:
            return
        self._r_any()
        if self._failed:
            return
        v__2 = self._val
        self._succeed(v__2)

    def _s_esc_char_11(self):
        p = self._pos
        errpos = self._errpos
        self._s_esc_char_12()
        if self._failed:
            self._succeed(None, p)
        else:
            self._rewind(p)
            self._errpos = errpos
            self._fail()

    def _s_esc_char_12(self):
        p = self._pos
        self._ch('x')
        if not self._failed:
            return
        self._rewind(p)
        self._ch('u')
        if not self._failed:
            return
        self._rewind(p)
        self._r_digit()
        if not self._failed:
            return
        self._rewind(p)
        self._r_eol()

    def _s_esc_char_13(self):
        self._ch('0')
        if self._failed:
            return
        self._s_esc_char_14()
        if self._failed:
            return
        self._succeed('\x00')

    def _s_esc_char_14(self):
        p = self._pos
        errpos = self._errpos
        self._r_digit()
        if self._failed:
            self._succeed(None, p)
        else:
            self._rewind(p)
            self._errpos = errpos
            self._fail()

    def _r_hex_esc(self):
        self._ch('x')
        if self._failed:
            return
        self._s_hex_esc_1()
        if self._failed:
            return
        v__2 = self._val
        self._succeed(self._fn_xtou(self._fn_cat(v__2)))

    def _s_hex_esc_1(self):
        vs = []
        i = 0
        cmin, cmax = [2, 2]
        while i < cmax:
            self._r_hex()
            if self._failed:
                if i >= cmin:
                    self._succeed(vs)
                    return
                return
            vs.append(self._val)
            i += 1
        self._succeed(vs)

    def _r_unicode_esc(self):
        self._ch('u')
        if self._failed:
            return
        self._s_unicode_esc_1()
        if self._failed:
            return
        v__2 = self._val
        self._succeed(self._fn_xtou(self._fn_cat(v__2)))

    def _s_unicode_esc_1(self):
        vs = []
        i = 0
        cmin, cmax = [4, 4]
        while i < cmax:
            self._r_hex()
            if self._failed:
                if i >= cmin:
                    self._succeed(vs)
                    return
                return
            vs.append(self._val)
            i += 1
        self._succeed(vs)

    def _r_element_list(self):
        self._r_value()
        if self._failed:
            return
        v__1 = self._val
        self._s_element_list_1()
        v__2 = self._val
        self._s_element_list_3()
        self._succeed(self._fn_cons(v__1, v__2))

    def _s_element_list_1(self):
        vs = []
        while True:
            p = self._pos
            self._s_element_list_2()
            if self._failed or self._pos == p:
                self._rewind(p)
                break
            vs.append(self._val)
        self._succeed(vs)

    def _s_element_list_2(self):
        self._r__filler()
        self._ch(',')
        if self._failed:
            return
        self._r_value()

    def _s_element_list_3(self):
        p = self._pos
        self._s_element_list_4()
        if self._failed:
            self._succeed([], p)
        else:
            self._succeed([self._val])

    def _s_element_list_4(self):
        self._r__filler()
        self._ch(',')

    def _r_member_list(self):
        self._r_member()
        if self._failed:
            return
        v__1 = self._val
        self._s_member_list_1()
        v__2 = self._val
        self._s_member_list_3()
        self._succeed(self._fn_cons(v__1, v__2))

    def _s_member_list_1(self):
        vs = []
        while True:
            p = self._pos
            self._s_member_list_2()
            if self._failed or self._pos == p:
                self._rewind(p)
                break
            vs.append(self._val)
        self._succeed(vs)

    def _s_member_list_2(self):
        self._r__filler()
        self._ch(',')
        if self._failed:
            return
        self._r_member()

    def _s_member_list_3(self):
        p = self._pos
        self._s_member_list_4()
        if self._failed:
            self._succeed([], p)
        else:
            self._succeed([self._val])

    def _s_member_list_4(self):
        self._r__filler()
        self._ch(',')

    def _r_member(self):
        p = self._pos
        self._s_member_1()
        if not self._failed:
            return
        self._rewind(p)
        self._s_member_3()

    def _s_member_1(self):
        self._s_member_2()
        if self._failed:
            return
        v__1 = self._val
        self._r__filler()
        self._ch(':')
        if self._failed:
            return
        self._r_value()
        if self._failed:
            return
        v__3 = self._val
        self._succeed([v__1, v__3])

    def _s_member_2(self):
        self._r__filler()
        self._r_string()

    def _s_member_3(self):
        self._s_member_4()
        if self._failed:
            return
        v__1 = self._val
        self._r__filler()
        self._ch(':')
        if self._failed:
            return
        self._r_value()
        if self._failed:
            return
        v__3 = self._val
        self._succeed([v__1, v__3])

    def _s_member_4(self):
        self._r__filler()
        self._r_ident()

    def _r_ident(self):
        self._r_id_start()
        if self._failed:
            return
        v__1 = self._val
        self._s_ident_1()
        v__2 = self._val
        self._succeed(self._fn_cat(self._fn_cons(v__1, v__2)))

    def _s_ident_1(self):
        vs = []
        while True:
            p = self._pos
            self._r_id_continue()
            if self._failed or self._pos == p:
                self._rewind(p)
                break
            vs.append(self._val)
        self._succeed(vs)

    def _r_id_start(self):
        p = self._pos
        self._r_ascii_id_start()
        if not self._failed:
            return
        self._rewind(p)
        self._r_other_id_start()
        if not self._failed:
            return
        self._rewind(p)
        self._s_id_start_1()

    def _s_id_start_1(self):
        self._r_bslash()
        if self._failed:
            return
        self._r_unicode_esc()

    def _r_ascii_id_start(self):
        p = self._pos
        self._range('a', 'z')
        if not self._failed:
            return
        self._rewind(p)
        self._range('A', 'Z')
        if not self._failed:
            return
        self._rewind(p)
        self._ch('$')
        if not self._failed:
            return
        self._rewind(p)
        self._ch('_')

    def _r_other_id_start(self):
        p = self._pos
        self._unicat('Ll')
        if not self._failed:
            return
        self._rewind(p)
        self._unicat('Lm')
        if not self._failed:
            return
        self._rewind(p)
        self._unicat('Lo')
        if not self._failed:
            return
        self._rewind(p)
        self._unicat('Lt')
        if not self._failed:
            return
        self._rewind(p)
        self._unicat('Lu')
        if not self._failed:
            return
        self._rewind(p)
        self._unicat('Nl')

    def _r_id_continue(self):
        p = self._pos
        self._r_ascii_id_start()
        if not self._failed:
            return
        self._rewind(p)
        self._r_digit()
        if not self._failed:
            return
        self._rewind(p)
        self._r_other_id_start()
        if not self._failed:
            return
        self._rewind(p)
        self._unicat('Mn')
        if not self._failed:
            return
        self._rewind(p)
        self._unicat('Mc')
        if not self._failed:
            return
        self._rewind(p)
        self._unicat('Nd')
        if not self._failed:
            return
        self._rewind(p)
        self._unicat('Pc')
        if not self._failed:
            return
        self._rewind(p)
        self._s_id_continue_1()
        if not self._failed:
            return
        self._rewind(p)
        self._ch('\u200c')
        if not self._failed:
            return
        self._rewind(p)
        self._ch('\u200d')

    def _s_id_continue_1(self):
        self._r_bslash()
        if self._failed:
            return
        self._r_unicode_esc()

    def _r_num_literal(self):
        p = self._pos
        self._s_num_literal_1()
        if not self._failed:
            return
        self._rewind(p)
        self._s_num_literal_2()
        if not self._failed:
            return
        self._rewind(p)
        self._s_num_literal_3()
        if not self._failed:
            return
        self._rewind(p)
        self._s_num_literal_5()
        if not self._failed:
            return
        self._rewind(p)
        self._s_num_literal_6()
        if not self._failed:
            return
        self._rewind(p)
        self._s_num_literal_7()

    def _s_num_literal_1(self):
        self._ch('-')
        if self._failed:
            return
        self._r_num_literal()
        if self._failed:
            return
        v__2 = self._val
        self._succeed(self._fn_strcat('-', v__2))

    def _s_num_literal_2(self):
        self._ch('+')
        if self._failed:
            return
        self._r_num_literal()
        if self._failed:
            return
        v__2 = self._val
        self._succeed(v__2)

    def _s_num_literal_3(self):
        self._r_dec_literal()
        if self._failed:
            return
        v__1 = self._val
        self._s_num_literal_4()
        if self._failed:
            return
        self._succeed(v__1)

    def _s_num_literal_4(self):
        p = self._pos
        errpos = self._errpos
        self._r_id_start()
        if self._failed:
            self._succeed(None, p)
        else:
            self._rewind(p)
            self._errpos = errpos
            self._fail()

    def _s_num_literal_5(self):
        self._r_hex_literal()
        if self._failed:
            return
        v__1 = self._val
        self._succeed(v__1)

    def _s_num_literal_6(self):
        self._str('Infinity')
        if self._failed:
            return
        self._succeed('Infinity')

    def _s_num_literal_7(self):
        self._str('NaN')
        if self._failed:
            return
        self._succeed('NaN')

    def _r_dec_literal(self):
        p = self._pos
        self._s_dec_literal_1()
        if not self._failed:
            return
        self._rewind(p)
        self._s_dec_literal_5()

    def _s_dec_literal_1(self):
        start = self._pos
        self._s_dec_literal_2()
        if self._failed:
            return
        end = self._pos
        self._val = self._text[start:end]

    def _s_dec_literal_2(self):
        self._r_dec_int_lit()
        if self._failed:
            return
        self._s_dec_literal_3()
        self._s_dec_literal_4()

    def _s_dec_literal_3(self):
        p = self._pos
        self._r_frac()
        if self._failed:
            self._succeed([], p)
        else:
            self._succeed([self._val])

    def _s_dec_literal_4(self):
        p = self._pos
        self._r_exp()
        if self._failed:
            self._succeed([], p)
        else:
            self._succeed([self._val])

    def _s_dec_literal_5(self):
        start = self._pos
        self._s_dec_literal_6()
        if self._failed:
            return
        end = self._pos
        self._val = self._text[start:end]

    def _s_dec_literal_6(self):
        self._r_frac()
        if self._failed:
            return
        self._s_dec_literal_7()

    def _s_dec_literal_7(self):
        p = self._pos
        self._r_exp()
        if self._failed:
            self._succeed([], p)
        else:
            self._succeed([self._val])

    def _r_dec_int_lit(self):
        p = self._pos
        self._s_dec_int_lit_1()
        if not self._failed:
            return
        self._rewind(p)
        self._s_dec_int_lit_3()

    def _s_dec_int_lit_1(self):
        self._ch('0')
        if self._failed:
            return
        self._s_dec_int_lit_2()

    def _s_dec_int_lit_2(self):
        p = self._pos
        errpos = self._errpos
        self._r_digit()
        if self._failed:
            self._succeed(None, p)
        else:
            self._rewind(p)
            self._errpos = errpos
            self._fail()

    def _s_dec_int_lit_3(self):
        self._r_nonzerodigit()
        if self._failed:
            return
        self._s_dec_int_lit_4()

    def _s_dec_int_lit_4(self):
        vs = []
        while True:
            p = self._pos
            self._r_digit()
            if self._failed or self._pos == p:
                self._rewind(p)
                break
            vs.append(self._val)
        self._succeed(vs)

    def _r_digit(self):
        self._range('0', '9')

    def _r_nonzerodigit(self):
        self._range('1', '9')

    def _r_hex_literal(self):
        self._s_hex_literal_1()
        if self._failed:
            return
        self._s_hex_literal_2()
        if self._failed:
            return
        v__2 = self._val
        self._succeed(self._fn_strcat('0x', self._fn_cat(v__2)))

    def _s_hex_literal_1(self):
        p = self._pos
        self._str('0x')
        if not self._failed:
            return
        self._rewind(p)
        self._str('0X')

    def _s_hex_literal_2(self):
        vs = []
        self._r_hex()
        if self._failed:
            return
        vs.append(self._val)
        while True:
            p = self._pos
            self._r_hex()
            if self._failed or self._pos == p:
                self._rewind(p)
                break
            vs.append(self._val)
        self._succeed(vs)

    def _r_hex(self):
        p = self._pos
        self._range('a', 'f')
        if not self._failed:
            return
        self._rewind(p)
        self._range('A', 'F')
        if not self._failed:
            return
        self._rewind(p)
        self._r_digit()

    def _r_frac(self):
        self._ch('.')
        if self._failed:
            return
        self._s_frac_1()

    def _s_frac_1(self):
        vs = []
        self._r_digit()
        if self._failed:
            return
        vs.append(self._val)
        while True:
            p = self._pos
            self._r_digit()
            if self._failed or self._pos == p:
                self._rewind(p)
                break
            vs.append(self._val)
        self._succeed(vs)

    def _r_exp(self):
        self._s_exp_1()
        if self._failed:
            return
        self._s_exp_2()
        self._s_exp_4()

    def _s_exp_1(self):
        p = self._pos
        self._ch('e')
        if not self._failed:
            return
        self._rewind(p)
        self._ch('E')

    def _s_exp_2(self):
        p = self._pos
        self._s_exp_3()
        if self._failed:
            self._succeed([], p)
        else:
            self._succeed([self._val])

    def _s_exp_3(self):
        p = self._pos
        self._ch('+')
        if not self._failed:
            return
        self._rewind(p)
        self._ch('-')

    def _s_exp_4(self):
        vs = []
        self._r_digit()
        if self._failed:
            return
        vs.append(self._val)
        while True:
            p = self._pos
            self._r_digit()
            if self._failed or self._pos == p:
                self._rewind(p)
                break
            vs.append(self._val)
        self._succeed(vs)

    def _r__whitespace(self):
        p = self._pos
        self._ch(' ')
        if not self._failed:
            return
        self._rewind(p)
        self._ch('\t')
        if not self._failed:
            return
        self._rewind(p)
        self._ch('\n')
        if not self._failed:
            return
        self._rewind(p)
        self._ch('\r')
        if not self._failed:
            return
        self._rewind(p)
        self._ch('\v')
        if not self._failed:
            return
        self._rewind(p)
        self._ch('\f')
        if not self._failed:
            return
        self._rewind(p)
        self._ch('\xa0')
        if not self._failed:
            return
        self._rewind(p)
        self._ch('\u2028')
        if not self._failed:
            return
        self._rewind(p)
        self._ch('\u2029')
        if not self._failed:
            return
        self._rewind(p)
        self._ch('\ufeff')
        if not self._failed:
            return
        self._rewind(p)
        self._unicat('Zs')

    def _r__comment(self):
        p = self._pos
        self._s__comment_1()
        if not self._failed:
            return
        self._rewind(p)
        self._s__comment_4()

    def _s__comment_1(self):
        self._str('//')
        if self._failed:
            return
        self._s__comment_2()

    def _s__comment_2(self):
        vs = []
        while True:
            p = self._pos
            self._s__comment_3()
            if self._failed or self._pos == p:
                self._rewind(p)
                break
            vs.append(self._val)
        self._succeed(vs)

    def _s__comment_3(self):
        p = '[^\r\n]'
        if p not in self._regexps:
            self._regexps[p] = re.compile(p)
        m = self._regexps[p].match(self._text, self._pos)
        if m:
            self._succeed(m.group(0), m.end())
            return
        self._fail()

    def _s__comment_4(self):
        self._str('/*')
        if self._failed:
            return
        while True:
            self._str('*/')
            if not self._failed:
                break
            self._r_any()
            if self._failed:
                break

    def _r__filler(self):
        vs = []
        while True:
            p = self._pos
            self._s__filler_1()
            if self._failed or self._pos == p:
                self._rewind(p)
                break
            vs.append(self._val)
        self._succeed(vs)

    def _s__filler_1(self):
        p = self._pos
        self._r__whitespace()
        if not self._failed:
            return
        self._rewind(p)
        self._r__comment()

    def _r_any(self):
        if self._pos < self._end:
            self._succeed(self._text[self._pos], self._pos + 1)
        else:
            self._fail()

    def _r_end(self):
        if self._pos == self._end:
            self._succeed(None)
        else:
            self._fail()

    def _ch(self, ch):
        p = self._pos
        if p < self._end and self._text[p] == ch:
            self._succeed(ch, self._pos + 1)
        else:
            self._fail()

    def _check_externs(self):
        errors = ''
        for ext in self._expected_externs:
            if ext not in self._externs:
                errors += f'Missing extern "{ext}"\n'
        for ext in self._externs:
            if ext not in self._expected_externs:
                errors += f'Unexpected extern "{ext}"\n'
        return errors.strip()

    def _err_offsets(self):
        lineno = 1
        colno = 1
        for i in range(self._errpos):
            if self._text[i] == '\n':
                lineno += 1
                colno = 1
            else:
                colno += 1
        return lineno, colno

    def _err_str(self):
        lineno, colno = self._err_offsets()
        if self._errpos == len(self._text):
            thing = 'end of input'
        else:
            thing = repr(self._text[self._errpos]).replace("'", '"')
        return '%s:%d Unexpected %s at column %d' % (
            self._path,
            lineno,
            thing,
            colno,
        )

    def _fail(self):
        self._val = None
        self._failed = True
        self._errpos = max(self._errpos, self._pos)

    def _range(self, i, j):
        p = self._pos
        if p != self._end and ord(i) <= ord(self._text[p]) <= ord(j):
            self._succeed(self._text[p], self._pos + 1)
        else:
            self._fail()

    def _rewind(self, newpos):
        self._succeed(None, newpos)

    def _str(self, s):
        for ch in s:
            self._ch(ch)
            if self._failed:
                return
        self._val = s

    def _succeed(self, v, newpos=None):
        self._val = v
        self._failed = False
        if newpos is not None:
            self._pos = newpos

    def _unicat(self, cat):
        p = self._pos
        if p < self._end and unicodedata.category(self._text[p]) == cat:
            self._succeed(self._text[p], self._pos + 1)
        else:
            self._fail()

    def _fn_cat(self, strs):
        return ''.join(strs)

    def _fn_cons(self, hd, tl):
        return [hd] + tl

    def _fn_strcat(self, a, b):
        return a + b

    def _fn_xtou(self, s):
        return chr(int(s, base=16))
